export const EDIT_SEND_ASSET_FORM = 'EDIT_SEND_ASSET_FORM'
export const EDIT_SEND_SYS_FORM = 'EDIT_SEND_SYS_FORM'

export const SEND_ASSET_IS_LOADING = 'SEND_ASSET_IS_LOADING'
export const SEND_ASSET_ERROR = 'SEND_ASSET_ERROR'
export const SEND_ASSET_RECEIVE = 'SEND_ASSET_RECEIVE'

export const SEND_SYS_IS_LOADING = 'SEND_SYS_IS_LOADING'
export const SEND_SYS_ERROR = 'SEND_SYS_ERROR'
export const SEND_SYS_RECEIVE = 'SEND_SYS_RECEIVE'
