export const CHANGE_FORM_TAB = 'CHANGE_FORM_TAB'

export const EDIT_SEND_ASSET_FORM = 'EDIT_SEND_ASSET_FORM'
export const EDIT_SEND_SYS_FORM = 'EDIT_SEND_SYS_FORM'

export const SEND_ASSET_IS_LOADING = 'SEND_ASSET_IS_LOADING'
export const SEND_ASSET_ERROR = 'SEND_ASSET_ERROR'
export const SEND_ASSET_RECEIVE = 'SEND_ASSET_RECEIVE'

export const GET_ASSETS_FROM_ALIAS_IS_LOADING = 'GET_ASSETS_FROM_ALIAS'
export const GET_ASSETS_FROM_ALIAS_RECEIVE = 'GET_ASSETS_FROM_ALIAS_RECEIVE'
export const GET_ASSETS_FROM_ALIAS_ERROR = 'GET_ASSETS_FROM_ALIAS_ERROR'

export const SEND_SYS_IS_LOADING = 'SEND_SYS_IS_LOADING'
export const SEND_SYS_ERROR = 'SEND_SYS_ERROR'
export const SEND_SYS_RECEIVE = 'SEND_SYS_RECEIVE'
