export const WALLET_GETINFO = 'WALLET_GETINFO'
export const WALLET_ALIASES = 'WALLET_ALIASES'
export const WALLET_UNFINISHED_ALIASES = 'WALLET_UNFINISHED_ALIASES'
export const WALLET_BLOCKCHAIN_INFO = 'WALLET_BLOCKCHAIN_INFO'
