export const WALLET_GETINFO = 'WALLET_GETINFO'
export const WALLET_ALIASES = 'WALLET_ALIASES'
export const WALLET_UNFINISHED_ALIASES = 'WALLET_UNFINISHED_ALIASES'
export const WALLET_BLOCKCHAIN_INFO = 'WALLET_BLOCKCHAIN_INFO'

export const WALLET_DASHBOARD_ASSETS_IS_LOADING = 'WALLET_DASHBOARD_ASSETS_IS_LOADING'
export const WALLET_DASHBOARD_ASSETS_ERROR = 'WALLET_DASHBOARD_ASSETS_ERROR'
export const WALLET_DASHBOARD_ASSETS_RECEIVE = 'WALLET_DASHBOARD_ASSETS_RECEIVE'

export const WALLET_DASHBOARD_TRANSACTIONS_IS_LOADING = 'WALLET_DASHBOARD_TRANSACTIONS_IS_LOADING'
export const WALLET_DASHBOARD_TRANSACTIONS_ERROR = 'WALLET_DASHBOARD_TRANSACTIONS_ERROR'
export const WALLET_DASHBOARD_TRANSACTIONS_RECEIVE = 'WALLET_DASHBOARD_TRANSACTIONS_RECEIVE'
